# Generated by Django 4.0.7 on 2022-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('types', models.CharField(max_length=120)),
                ('ratings', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('attributes', models.CharField(max_length=120)),
            ],
        ),
    ]
