# Generated by Django 4.0.3 on 2022-09-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poi',
            old_name='types',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
