# Generated by Django 4.0.7 on 2022-09-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0002_rename_types_poi_type_alter_poi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='ratings',
        ),
        migrations.AddField(
            model_name='poi',
            name='guid',
            field=models.PositiveIntegerField(default=999999, max_length=6),
        ),
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
