# Generated by Django 4.0.7 on 2022-09-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_remove_poi_attributes_remove_poi_ratings_poi_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='guid',
            field=models.PositiveIntegerField(default=999999),
        ),
    ]
