# Generated by Django 4.0.7 on 2022-09-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0005_poi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='name',
            field=models.BooleanField(default=True),
        ),
    ]
