# Generated by Django 4.0.7 on 2022-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0006_poi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='guid',
            field=models.PositiveIntegerField(default=999999, unique=True),
        ),
    ]
