# Generated by Django 4.0.7 on 2022-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0008_remove_poi_name_alter_poi_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='name',
            field=models.CharField(default='null', max_length=120, null=True),
        ),
    ]
