# Generated by Django 4.0.7 on 2022-09-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0007_alter_poi_guid'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='guid',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='poi.poi', to_field='guid'),
        ),
    ]
