# Generated by Django 4.0.7 on 2022-11-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Average'), (3, 'High')], default=2),
        ),
    ]
